wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.14.0
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.13
    start_time: 1680485520.957543
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      2:
      - 1
      - 5
      - 53
      - 55
      3:
      - 15
      - 19
      - 23
      4: 3.9.13
      5: 0.14.0
      8:
      - 5
action_space_dim:
  desc: null
  value: 4
degenerated_state_space_dim:
  desc: null
  value: 80
episode_len:
  desc: null
  value: 80
grid_size:
  desc: null
  value: 100
hidden_layer_size:
  desc: null
  value: 32
num_episodes:
  desc: null
  value: 100
num_epochs:
  desc: null
  value: 100
num_policy:
  desc: null
  value: 100
observation_space_dim:
  desc: null
  value: 4
test_split:
  desc: null
  value: 0.1
train_split:
  desc: null
  value: 0.8
val_split:
  desc: null
  value: 0.1
