wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.14.0
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.16
    start_time: 1680320505.165366
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      2:
      - 1
      - 5
      - 53
      - 55
      3:
      - 19
      - 23
      4: 3.9.16
      5: 0.14.0
      8:
      - 5
action_space_dim:
  desc: null
  value: 4
degenerated_state_space_dim:
  desc: null
  value: 80
episode_len:
  desc: null
  value: 80
grid_size:
  desc: null
  value: 5
hidden_layer_size:
  desc: null
  value: 8
num_episodes:
  desc: null
  value: 10
num_policy:
  desc: null
  value: 10
observation_space_dim:
  desc: null
  value: 4
test_split:
  desc: null
  value: 0.1
train_split:
  desc: null
  value: 0.8
val_split:
  desc: null
  value: 0.1
