wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.14.0
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.13
    start_time: 1680489047.84346
    t:
      1:
      - 1
      - 5
      - 50
      - 53
      - 55
      3:
      - 15
      - 23
      4: 3.9.13
      5: 0.14.0
      8:
      - 5
